### ISSUE TITLE
Have you used chinese fonts for style_transfer?

### ISSUE THREAD

**Issue by ezio1320** [ganji15/HiGAN#2]
It's very interesting and exciting work.

The fonts style_trans in English fonts is very excellent!  i wanna to know have you try this gan-net in chinese fonts。

（从论文来看，你们的提出的Higan网络在英文字上的风格迁移效果非常的好，不知道你们之前有没有试过在中文上的效果。感觉你们的工作有趣且有用，期待收到回复！）

**Comment by ganji15** [comment]
你好，我们之前都只在英文数据上做的，中文数据没有试过。生成中文文本会更难一点，因为汉字类别比较多，结构也更复杂。具体操作起来技术实现可能大致一样，主要区别可能是要设计一个更好的CNN生成器或者加更多的技巧 (trick)来保证正确地生成汉字的各处细节。我们后续有可能会尝试在中文数据上试一下效果。

**Comment by ezio1320** [comment]
> 你好，我们之前都只在英文数据上做的，中文数据没有试过。生成中文文本会更难一点，因为汉字类别比较多，结构也更复杂。具体操作起来技术实现可能大致一样，主要区别可能是要设计一个更好的CNN生成器或者加更多的技巧 (trick)来保证正确地生成汉字的各处细节。我们后续有可能会尝试在中文数据上试一下效果。

期待在中文数据集上的效果
