### ISSUE TITLE
Question about IAM images

### ISSUE THREAD

**Issue by SB2020-eye** [ganji15/HiGAN#4]
Hi. I have registered with IAM. The download page looks like this:

![image](https://user-images.githubusercontent.com/56878280/135637167-efd7d39c-5390-4343-9843-81540199ffee.png)
1. Do I need any of this, or do I just need your hdf5 files?
2. If I need something here, do I download all of these you see listed above, or just the ones with pngs, or some other subset of them?
3. Where do I put them (within the HiGAN directory)?

Thank you!

**Comment by ganji15** [comment]
Hi，@SB2020-eye,

You just need those hdf5 files. 

You can simply download those hdf5 files (trnvalset_words32.hdf5, testset_words32.hdf5, testset_words32d_OrgSz.hdf5) and then put them into the './data/' directory. After that,  the training  can be started with the command  ```python main.py --config ./configs/gan_iam.yml```.

**Comment by SB2020-eye** [comment]
Thanks very much. 😄
