### ISSUE TITLE
How to introduce a new handwriting style

### ISSUE THREAD

**Issue by SB2020-eye** [ganji15/HiGAN#5]
How would you go about using HiGAN to imitate a new handwriting style (not in the IAM database)?

**Comment by ganji15** [comment]
Hi，@SB2020-eye

After the training, we suppose that the style extractor of HiGAN can learn to encode any given handwriting image ```x``` (even for unseen handwriting images in inference) into a latent style code ```s```, and this code may indicate the unique style of the given handwriting image. Therefore, the generator will synthesize new handwriting images with a similar style conditioned on the encoded style code ```s```. In our experiments, the model is trained with the training & validate sets, and then is evaluated on the test set (i.e., unseen handwriting images of unseen writers).

**Comment by SB2020-eye** [comment]
Thank you so much for your response. This is very helpful to know.

I am very much a novice at programming. So I apologize for my very basic level of questioning. But would you mind guiding me through the steps for doing this?

(For example, where would I put my new handwriting image file? And then how would I run HiGAN to make it output novel text input in that style?)

And are there any limitations regarding style, image size, glyph size, etc?

**Comment by ganji15** [comment]
I. Steps:
1. Pack your new handwriting images into an hdf5 file (refers to [issue #3)](https://github.com/ganji15/HiGAN/issues/3);
2. Rename the generated hdf5 file as  "testset_words32.hdf5" and put it to "./data/iam/" directory;
3. Excute ```python eval_demo.py --config ./configs/gan_iam.yml --ckpt [pretrained_model_file] --mode style```.

II. Limitation:
1. only the handwriting style is supported;
2. the size of out image is "[32, 16 * len(text)]".
